### ISSUE TITLE
Missing documentation on /spy

### ISSUE THREAD

**Issue by Salanto** [RealKaiser/tsuserverCC#16]
This command seems to allow authenticated players, i.E mods to get the chatlogs of another area without being in it.

**Comment by OfficialLawyerEmporium** [comment]
You guys taking pull requests for this issue, or just leaving it to the person who originally wrote /spy? Going through the code myself right now, figure I may as well document it.

-[LNCR] Steel

**Comment by OfficialLawyerEmporium** [comment]
Initial look over the code, spies lean on send_owner_command for areas they're spying on, like CMs it looks like. send_owner_command is called as part of the IC and OOC message handlers, so yeah, looks like someone spying on a room can pick up both chat logs and OOC message logs.

You can check by looking at:
send_owner_command (part of area_manager)
net_cmd_ms (IC message handler, aoprotocol.py)
net_cmd_ct (OOC message handler, aoprotocol.py)

References variables:
spying (part of client_manager)
spies (part of area_manager)

**Comment by Salanto** [comment]
Thanks for the infodump. Should make it very easy for the maintainer to write appropriate documentation.

**Comment by OfficialLawyerEmporium** [comment]
No problem, matey. I'll leave it there for now, though if you want some documentation in the code itself, I could put together a little push with what I wrote up.

-[LNCR] Steel
